etetoolkit/ete

ete3/ncbi_taxonomy/ncbiquery.py
pysqlite2 was causing an error on import on my machine.
As far as I can tell this module has been mostly deprecated in favour of sqlit3.
As the rest of the module uses sqlite3 and sqlite3's dbapi2 interface seems to achieve the same task as the original pysqlite2 code I've updated this tiny bit of code to now use sqlite3.dbapi2.
=> get_fuzzy_name_translation in ncbi_taxonomy sqlite update

ete3/treeview/faces.py
I added a parameter "bold" in faces.py  to class TextFace that determines if textface will be printed in bold. The default is False. The implementation is in the method _get_font
=> Added boolean argument bold to TextFace

sdoc/tutorial/tutorial_trees.rst
Line 371 in [tutorial_trees.rst](https://github.com/etetoolkit/ete/blob/master/sdoc/tutorial/tutorial_trees.rst)
requires `tree` to be `t` in Line 368.
=> Minor variable correction in tutorial_trees.rst

examples/general/custom_search.py, examples/general/get_distances_between_nodes.py, examples/general/prune_tree.py, examples/general/rooting_subtrees.py, examples/general/rooting_trees.py, sdoc/old_tutorial/examples/custom_search.py, sdoc/old_tutorial/examples/get_distances_between_nodes.py, sdoc/old_tutorial/examples/prune_tree.py, sdoc/old_tutorial/examples/rooting_subtrees.py, sdoc/old_tutorial/examples/rooting_trees.py, sdoc/tutorial/tutorial_trees.rst
In files [tutorial_trees.rst](https://github.com/etetoolkit/ete/blob/master/sdoc/tutorial/tutorial_trees.rst), [general/prune_tree.py](https://github.com/etetoolkit/ete/blob/master/examples/general/prune_tree.py), [examples/prune_tree.py](https://github.com/etetoolkit/ete/blob/master/sdoc/old_tutorial/examples/prune_tree.py)
line `t = Tree('((((H,K),(F,I)G),E),((L,(N,Q)O),(P,S)));')` requires format=1 as additional argument as default format is 0.
Minor corrections in other files.
=> Few more small corrections in tutorial related files

ete3/ncbi_taxonomy/ncbiquery.py
If ValueError is raised,then the taxid represents a single node.Hence,a single-node annotated tree is returned from get_topology method.
=> Minor change to get_topology method

ete3/_ph.py
Noticed a syntax error on pip install:
```
$ pip3 install ete3==3.0.0b33
<<<SNIP>>>
Installing ete3 script to ~/.local/bin
File "~/.local/lib/python3.5/site-packages/ete3/_ph.py", line 69
except Exception, e:
^
SyntaxError: invalid syntax
- Done! -
Successfully installed ete3
Cleaning up...
```
=> Python3 compat fix for _ph.py

ete3/parser/newick.py, ete3/test/test_tree.py
quoted node names were including the quotes in the node name, which is not the behavior we want
=> quoted node names don't include the quotes

ete3/tools/ete_ncbiquery.py
ete3 ncbiquery does not takes in account the --db taxa.sqlite file provided.
as the call to NCBITaxa is called with no value at init so does not use args.dbfile value
this simple patch allows to specify the dbfile to use 
Eric
=> do not ignore dbfile argument

ete3/ncbi_taxonomy/ncbiquery.py, ete3/tools/ete_ncbiquery.py
We provide ete tools thru a centralized instalation on the HPC cluster.
compute node does not have internet access, so user can't create the db file (taxa.sqlite) using http ncbi access.
with this modifications, users can provide a local taxdump.tar.gz file and create their taxa.sqlite db.
furthermore we mirror taxonomy databases from the ncbi, with this modification we will be abble to update the taxa.sqlite on a centralised way and provide a up to date db to all our users.
regards
Eric
=> allow creation of db file from local taxdump file + add create db option

ete3/evol/evoltree.py, ete3/tools/ete_evol.py, sdoc/tutorial/tutorial_adaptation.rst
- ete_evol tool: output directory names could be too long for filesystem, this is now fixed using md5 digestion of the model name and the newick tree. directory name still contain the begining of the model name in order to keep them "human readable"
- evolTree: documentation updated in order to describe better models M1 and M2 which names are not coinciding with the ones in PAML documentation
... this is more comment than the corresponding code XD
=> ete_evol: fixed problem with long ouput directory names and updated documentation

ete3/coretype/tree.py
=> tree.py: documentation spelling fix

ete3/coretype/tree.py
Fixing tree.render() dpi description to accurately reflect the default value of 90 dpi.
=> Fix tree.render() documentation

ete3/coretype/tree.py
Example for tree.write() used old method. Is now updated.
=> fix tree.write() documentation

ete3/ncbi_taxonomy/ncbiquery.py
This is just a minor tweak to avoid useless download when the taxdump.tar.gz file happens to be already present in the current working directory, and is up-to-date (according to the md5 sum). This actually happened to me. I did a test on linux with python 3.6.
=> Avoid downloading taxdump.tar.gz if present.

ete3/coretype/tree.py, ete3/evol/evoltree.py, ete3/evol/utils.py, ete3/tools/ete_build_lib/apps.py, ete3/tools/ete_build_lib/seqio.py, ete3/tools/ete_evol.py, ete3/treeview/faces.py
- Python3 compatibility issues fixed, in ete evol tool and test_ete_evol (string encoding issues).
- PyQt5 compatibility
- chi2 test was missing variables when high df (also ete evol now uses chi2 from scipy when scipy is installed)
- Tree.prune is now much faster when list of input nodes are TreeObjects
- removed reference to _nid in Tree.sort_descendants function
- fixed typo in warning to install external apps
=> Fix Python3/pyQt4 compatibility issues; bug in chi2 (ete_evol); faster prune

ete3/webplugin/webapp.py
The file needs to be open as binary, or it fails when using python3.
=> Fix python3

ete3/test/test_ncbiquery.py
update unittest of test_ncbiquery in regard to new NCBI Taxonomies of Homo
ref:
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9605
=> update ncbiquery unittest corresponding NCBI #443

ete3/ncbi_taxonomy/ncbiquery.py
if taxdump.tar.gz is not up-to-date, download the latest version and replace the outdated one
=> Handling outdated taxdump file etetoolkit#416

ete3/ncbi_taxonomy/ncbiquery.py
if taxid deprecated, then translate it to its descendants
=> read synonyms table in get_descendant_taxa() if taxid deprecated #436

ete3/coretype/tree.py, ete3/parser/newick.py, ete3/test/test_tree.py
=> returns itself if same node is provided as only argument of get_common_ancestor 

ete4/smartview/ete/draw.pyx
This change makes the names of the collapsed nodes appear in order
in their summary string representation.
Before, we used to put them together with a set, so the order was
not preserved. Using a list instead was no good, since for big
trees the speed difference to remove duplicates was tremendous
(~100x slower).
Ideally, we would have used something similar to an OrderedSet in
python, but there is no such thing in the standard library. Instead
we now use an OrderedDict with keys the names of the nodes we want
and values set to None.
They work like a charm :)
=> Summarize the names of collapsed nodes respecting their original order.

ete4/coretype/tree.pyx, ete4/parser/newick.pyx
Added newick formats (and quoted_names flag) to ete4 write_newick() function
TODO: newick parser tests
TO CONSIDER:
change quoted_names flag by calling quote() where only names containing newick-illegar chars are quoted
=> Newick formats

.gitignore, ete3/ncbi_taxonomy/ncbiquery.py, sdoc/reference/reference_ncbi.rst
This small change allows the user to define the location of the `taxa.sqlite`
Right now, `taxa.sqlite` must always be in `$HOME/.etetoolkit` which is sometimes problematics when using etetools in containers (Docker, Singularity) and HPC/Cloud that don't always have a `$HOME` directory
**Before:**
```python
>>> import os
>>> os.listdir("/Users/borry/Desktop/etetoolkit")
[]
>>> from ete3 import NCBITaxa
>>> ncbi = NCBITaxa(dbfile="/Users/borry/Desktop/etetoolkit/taxa.sqlite")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/borry/Documents/GitHub/ete/ete3/ncbi_taxonomy/ncbiquery.py", line 116, in __init__
raise ValueError("Cannot open taxonomy database: %s" % self.dbfile)
ValueError: Cannot open taxonomy database: …
```
=> Allow custom location for taxa.sqlite

ete3/evol/parser/codemlparser.py
Newer versions of Python (>=3.8) emit a syntax warning when the _is_ operator is used with string literals. This happens in codemlparser.py when a string is compared with '\n', which causes an annoying syntax warning when importing ete3.
This fixes #504 (which references a description of the syntax warning: https://bugs.python.org/issue34850).
=> replaced 'is' with '=='

ete3/ncbi_taxonomy/ncbiquery.py, sdoc/tutorial/tutorial_ncbitaxonomy.rst
I ran into problems using the NCBITaxa class.
Initiating the class always triggers a check if the current data base is not up to date. This causes other processes to throw sqlite errors when they want to access the database at the same time.
Therefore I added an option on initializing the class to not update the database. The default in this pull request still is that an automatic update is triggered, hence this pull request is down stream compatible. If any software relies on the automatic update on class initialization.
I changed the official documentation to clarify the way how the data base can be updated. And further added a few explanation on some option regarding the initialization of the class and a formatting error.
Currently I need some try and except statement to catch the …
=> Ncbi update option

ete3/coretype/tree.py
change duplicate "attr_t2" to "unrooted_trees," which is consistent with the explanation for this parameter in the docstring, "If True, consider trees as unrooted"
=> Fix docstring typo in TreeNode.robinson_foulds

ete3/orthoxml/_orthoxml.py
In ete3, when we got the orthoXML output, there was a b' prefix in almost all the strings exported. This was due to the '.encode(ExternalEncoding)' statements, which are not necessary anymore, thus I've dropped them.
I'm not sure if this can cause any further problem but it is valid as a provisional solution for this.
=> Fixed b' prefix error

ete3/treeview/main.py
This PR allows any callable object to be set as the layout function of a `TreeStyle` object.
Currently, only objects whose type match `types.FunctionType` or `types.MethodType` are allowed. This behavior excludes otherwise valid Python callables, e.g. partial functions created with `functools.partial`, or any used-defined class that implements `__call__`, irrespective of whether the actual call would succeed or not.
The PR fixes this by using the `callable` built-in function for checking the layout function's type.
=> allow any callable as argument to TreeStyle.set_layout_fn

ete3/treeview/drawer.py, ete3/treeview/main.py, ete3/treeview/qt4_circular_render.py, ete3/treeview/qt4_render.py
Resolves #568. 
Changes:  
1) Remove excess whitespace in semicircle layouts.
```
from ete3 import Tree, TreeStyle
t = Tree()
t.populate(30)
ts = TreeStyle()
ts.show_leaf_name = True
ts.mode = "c"
ts.arc_start = -180 # 0 degrees = 3 o'clock
ts.arc_span = 180
t.render('example.png', tree_style=ts)
```
2) Added ability to bring leaf nodes closer to center in circular layouts by reducing the length of each leaf's extra branch line as much as possible while avoiding intersecting QGraphicsItems. The 'pack_leaves' parameter in TreeStyle is used to turn this feature on. 
```
from ete3 import Tree, TreeStyle, CircleFace
t = Tree()
t.populate(15)
ts = TreeStyle()
ts.scale = 100
ts.show_leaf_name = False
ts.mode = 'c'
ts.arc_start = -45
ts.arc_span = 90
ts.force_topology = True
ts.pack_leaves = …
```
=> Resolve #568. Tight adjustment of faces in circular mode
